workflows:
  android-build:
    name: Build Android APK
    environment:
      vars:
        ANDROID_SDK_ROOT: /opt/android-sdk
      node: latest
    scripts:
      - echo "Starting Android build without gradlew"
      - gradle assembleRelease
    artifacts:
      - app/build/outputs/apk/release/*.apk
